<p style="text-align: justify;" align="center"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><strong>Privacy Policy</strong></span></span></p>
<p style="text-align: justify;"><br /> </p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Times New Roman', serif;"><span style="font-size: medium;"><span style="color: #000000;"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;">Krishnav skill and marketing pvt. ltd, accessible from <a href="https://housegoods.co.in/">https://housegoods.co.in</a>, one main priorities is the privacy of our visitors. This privacy policy documents contains types of information that is collected and recorded by HOUSE GOODS and hoe we use it. HOUSE GOODS is online product selling site. If you have additional question or requires more information about our Privacy Policy, do not hesitate to contact us.</span></span></span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="color: #000000;"> <span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;">This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to information that they shared and collect in HOUSE GOODS. This policy is not applicable to any information collected offline or via channels other than this website.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">HOW WE USE YOUR INFORMATION</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">We use the information we collect in various ways including to:</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">Provide , operate and maintain our website.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">Improve, personalize and expand our website.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">Understand and analyze how you use our website.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">Develop new products ,service, features and functionality.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">Communicate with you, either directly or through one of our partners , including for customer service to provide you with updates and other information relating to the websites and for marketing and promotional purposes.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">Send you emails.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">You may consult this list to find the Privacy Policy for each of the advertising partners of HOUSE GOODS. Third-party ad servers or ad networks uses technologies like cookies, java script or web are used in their respective advertisements. HOUSE GOODS has no access to or control over these cookies that are used by third-party advertisers.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in and/ or monitor and guide their online activity. We does not knowingly collect any personal information from children. If you think that your child provided this kind of information on our websites, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">We may update our privacy policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page, prior to the change becoming effective and update the &ldquo;effective date&rdquo; at the top of this Privacy Policy.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">Contact us.</span></span></span></p>
<p style="text-align: justify;" align="justify"><span style="font-family: 'Abyssinica SIL';"><span style="font-size: medium;"><span style="color: #000000;">If you n have question about privacy policy .Please contact to our mail id :- customercare@housegoods.co.in</span></span></span></p>
