<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
 
</head>
<body>
    <div style="padding:20px">
    <Br/>
<h1 align="center"><span style="color: #000000;"><span style="font-family: 'Trebuchet MS', serif;">Privacy Policy</span></span></h1>


<p align="justify"><span style="color: #666666;"><span style="font-family: 'Roboto Slab', serif;"><span style="font-size: large;">Personal Information</span></span></span></p>
<hr/>
<p align="justify"><span style="color: #333333;"><span style="font-family: lato, serif;"><span style="font-size: medium;">Vegansfresh Organics Pvt. Ltd. (&ldquo;VOPL&rdquo;)is the licensed owner of the brand &ldquo;Vegans Fresh&rdquo; and the website vegansfresh.com (&rdquo;The Site&rdquo;). VOPL respects your privacy. This Privacy Policy provides succinct details about how your data is collected and used by VOPL on the Site. As a visitor to the Site/ Customer, you are advised to please read the Privacy Policy carefully. By accessing the services provided by the Site you agree to the collection and use of your data by VOPL in the manner provided in this Privacy Policy.&nbsp;</span></span></span></p>
<hr/>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="color: #666666;"><span style="font-family: 'Roboto Slab', serif;"><span style="font-size: large;">What information is, or maybe, collected from you?</span></span></span></p>
<p align="justify"><span style="color: #333333;"><span style="font-family: lato, serif;"><span style="font-size: medium;">As part of the registration process on the Site, VOPL may collect the following personally identifiable information about you: Name including first and last name, email address, mobile phone number and contact details, Postal code, Demographic profile (like your age, gender, occupation, education, address etc.) and information about the pages on the site you visit/access, the links you click on the site, the number of times you access the page and any such browsing information.&nbsp;</span></span></span></p>
<hr/>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="color: #666666;"><span style="font-family: 'Roboto Slab', serif;"><span style="font-size: large;">How do we collect the Information</span></span></span></p>
<p align="justify"><span style="color: #333333;"><span style="font-family: lato, serif;"><span style="font-size: medium;">VOPL will collect personally identifiable information about you only as part of a voluntary registration process, on-line survey or any combination thereof. The Site may contain links to other Web sites. VOPL is not responsible for the privacy practices of such Web sites which it does not own, manage or control. The Site and third-party vendors, including Google, use first-party cookies (such as the Google Analytics cookie) and third-party cookies (such as the DoubleClick cookie) together to inform, optimize, and serve ads based on someone's past visits to the Site.&nbsp;</span></span></span></p>
<hr/>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="color: #666666;"><span style="font-family: 'Roboto Slab', serif;"><span style="font-size: large;">How is the information used?</span></span></span></p>
<p align="justify"><span style="color: #333333;"><span style="font-family: lato, serif;"><span style="font-size: medium;">VOPL will use your personal information to provide personalized features to you on the Site and to provide for promotional offers to you through the Site and other channels. VOPL will also provide this information to its business associates and partners to get in touch with you when necessary to provide the services requested by you. VOPL will use this information to preserve transaction history as governed by existing law or policy. VOPL may also use contact information internally to direct its efforts for product improvement, to contact you as a survey respondent, to notify you if you win any contest; and to send you promotional materials from its contest sponsors or advertisers. VOPL will also use this information to serve various promotional and advertising materials to you via display advertisements through the Google Ad network on third party websites. You can opt-out of Google Analytics for Display Advertising and customize Google Display Network ads using the Ads Preferences Manager. Information about Customers on an aggregate (excluding any information that may identify you specifically) covering Customer transaction data and Customer demographic and location data may be provided to partners of VOPL for the purpose of creating additional features on the website, creating appropriate merchandising or creating new products and services and conducting marketing research and statistical analysis of customer behaviour and transactions.</span></span></span></p>
<hr/>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="color: #666666;"><span style="font-family: 'Roboto Slab', serif;"><span style="font-size: large;">With whom your information will be shared</span></span></span></p>
<p align="justify"><span style="color: #333333;"><span style="font-family: lato, serif;"><span style="font-size: medium;">VOPL will not use your financial information for any purpose other than to complete a transaction with you. VOPL does not rent, sell or share your personal information and will not disclose any of your personally identifiable information to third parties. In cases where it has your permission to provide products or services, you've requested and such information is necessary to provide these products or services with the information may be shared with VOPL&rsquo;s business associates and partners. VOPL may, however, share consumer information on an aggregate with its partners or third parties where it deems necessary. In addition, VOPL may use this information for promotional offers, to help investigate, prevent or take action regarding unlawful and illegal activities, suspected fraud, potential threat to the safety or security of any person, violations of the Site&rsquo;s terms of use or to defend against legal claims; special circumstances such as compliance with subpoenas, court orders, requests/order from legal authorities or law enforcement agencies requiring such disclosure.&nbsp;</span></span></span></p>
<hr/>
<p align="justify">&nbsp;</p>
<p align="justify"><span style="color: #666666;"><span style="font-family: 'Roboto Slab', serif;"><span style="font-size: large;">How do we protect your information?</span></span></span></p>
<p align="justify"><span style="color: #333333;"><span style="font-family: lato, serif;"><span style="font-size: medium;">To protect against the loss, misuse, unauthorised access, damage and alteration of the information under its control, VOPL has in place appropriate and reasonable security measures and safeguards, in compliance with applicable laws. For example, VOPL servers are accessible only to authorised personnel and your information is shared with the authorised personnel on a need to know basis to complete the transaction and to provide the services requested by you. Although VOPL will endeavour to safeguard the confidentiality of your personally identifiable information, transmissions made by means of the Internet cannot be made absolutely secure. By using this Site, you agree that VOPL will have no liability for disclosure of your information due to errors in transmission or unauthorized acts of third parties. By using this Site or providing information, you agree (i) that we can communicate with you electronically regarding security, privacy, and administrative issues relating to your use of the Site; and (ii) that we can take adequate physical, managerial, and technical safeguards to preserve the integrity and security of your data till the time you use the Site or the services provided by the Site (directly or indirectly).</span></span></span></p>
<hr/>
<p align="justify"><span style="color: #666666;"><span style="font-family: 'Roboto Slab', serif;"><span style="font-size: large;">How can you correct inaccuracies in the information?</span></span></span></p>
<p align="justify"><span style="color: #333333;"><span style="font-family: lato, serif;"><span style="font-size: medium;">To correct or update any information you have provided, the Site allows you to do it online. In the event of loss of access details, you can send an email to: support@vegansfresh.com&nbsp;</span></span></span></p>
<p align="justify"><span style="color: #666666;"><span style="font-family: 'Roboto Slab', serif;"><span style="font-size: large;">Policy updates</span></span></span></p>
<p align="justify"><span style="color: #333333;"><span style="font-family: lato, serif;"><span style="font-size: medium;">VOPL reserves the right to change or update this policy at any time. Such changes shall be effective immediately upon posting to the Site.&nbsp;</span></span></span></p>
<p align="justify"><span style="color: #666666;"><span style="font-family: 'Roboto Slab', serif;"><span style="font-size: large;">Contact Information</span></span></span></p>
<p align="justify"><a name="_GoBack"></a> <span style="color: #333333;"><span style="font-family: lato, serif;"><span style="font-size: medium;">Vegansfresh Organics Pvt. Ltd.,<br /> Plot No.2, Khasra No 15/17,<br /> Ground Floor, Main Sewa Dham Road, Mandoli Industrial Area, Delhi-110093 India<br /> Tel.: <br /> Email id: support@vegansfresh.com&nbsp;</span></span></span></p>
<p align="justify">&nbsp;</p>
</div>
</body>
</html>