<p align="center"><span style="font-size: xx-large;">Term And Condition.</span></p>
<p><span style="font-size: large;">Personal Information.</span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">1.Suzo daily needs.&rdquo; is a trademark of Suzo daily needs Private Limited, a company incorporated under the Companies Act, 2013 with its registered office at&nbsp;</span></span></span><span style="color: #222222;"><span style="font-family: Arial, serif;"><span style="font-size: medium;">PL NO. B-11/10 FL NO. SF-404 DLF ANKUR VIHAR, Loni, Ghaziabad, Delhi 201102.</span></span></span><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;">The domain name&nbsp;www.suzodailyneeds.in&nbsp;is owned by the Company. The Company holds a FSSAI license, bearing no. : 22720105000246.</span></span></p>
<h3 class="western"><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;">Services Overview</span></span></h3>
<h3 class="western"><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;">The Company is not and cannot be a party to any transaction between you and the third party sellers, or have any control, involvement or influence over the products purchased by you from such third party sellers or the prices of such products charged by such third-party sellers. The Company therefore disclaims all warranties and liabilities associated with any products offered on the Marketplace.</span></span></h3>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">Services on the Marketplace are available to only select geographies in India, and are subject to restrictions based on business hours and days of third party sellers.</span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">Transactions through the Marketplace may be subject to a delivery charge where the minimum order size is not met. You will be informed of such delivery charges at the stage of check-out for a transaction through the Marketplace.</span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;"><strong>Eligibility</strong></span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">Persons who are &ldquo;incompetent to contract&rdquo; within the meaning of the Indian Contract Act, 1872 including minors, un-discharged insolvents etc. are not eligible to use/access the Marketplace.</span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">However, if you are a minor, i.e. under the age of 18 years, you may use/access the Marketplace under the supervision of an adult parent or legal guardian who agrees to be bound by these Terms of Use. You are however prohibited (even under provision) from purchasing any product(s) which is for adult consumption, the sale of which to minors is prohibited.</span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">The Marketplace is intended to be a platform for end-consumers desirous of purchasing product(s) for domestic self-consumption. If you are a retailer, institution, wholesaler or any other business user, you are not eligible to use the Marketplace to purchase products from third-party sellers, who have been granted access to the Marketplace to display and offer their products for sale through the Marketplace.</span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">The Company, in its sole discretion and without liability, reserves the right to terminate or refuse your registration, or refuse to permit use/access to the Marketplace, if: (i) it is discovered or brought to notice that you do not conform to the eligibility criteria, or (ii) the Company has reason to believe (including through evaluating usage patterns) that the eligibility criteria is not met/is violated by a user, or (iii) may breach the terms of this User Agreement.</span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">In order to determine compliance with eligibility criteria, the Company inter alia uses an algorithm and/or pre-determined criteria based technology and accordingly, from time to time, your usage may be restricted or blocked on account of overlap with such algorithms/predetermined criteria. In such cases, if you are a genuine domestic user of the Platform, please contact us for assistance.</span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;"><strong>Account &amp; Registration Obligations</strong></span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">All users must register and log in for placing orders on the Marketplace. You must keep your account and registration details current and correct for all communications related to your purchases from the Marketplace. By agreeing to the Terms of Use, the user agrees to receive promotional or transactional communication and newsletters from the Company and its partners. The user can opt out from such communication and/or newsletters either by or by contacting the customer services team of Marketplace and placing a request for the same.</span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">As part of the registration process on the Marketplace, the Company may collect the following personally identifiable information about you, including but not limited to Name , email address, age, address mobile phone number and other contact details, demographic profile (like your age, gender, occupation, education, address etc.) and information about the pages on the Marketplace you visit/access, the links you click on the Marketplace, the number of times you access a particular page/feature and any such information. Information collected about you is subject to the Privacy Policy of the Company</span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;"><strong>Pricing</strong></span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">The Company aims to ensure that prices of all products offered for sale are true and correct.&nbsp;</span></span></span><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;"><em>However, from time to time, the prices of certain products may not be current or may be inaccurate on account of technical issues, typographical errors or incorrect product information provided to the Company by third-party sellers. In each such case, notwithstanding anything to the contrary, the Company reserves the right to cancel the order without any further liability.</em></span></span></span></p>
<p><span style="color: #403e3e;"><span style="font-family: Helvetica, serif;"><span style="font-size: large;">Subject to the foregoing, the price mentioned at the time of ordering a product shall be the price charged at the time of delivery, provided that no product offered for sale on the Marketplace will be sold at a price higher than its MRP (Maximum Retail Price).</span></span></span></p>
<h3 class="western"><br /> </h3>
<p><br /> </p>
<p><br /> </p>
<p><br /> </p>
<p><br /> </p>
<p>&nbsp;</p>
<p><br /> </p>
